trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  location: 'eastus'
  rgName: 'testRG'

stages:
  - stage: DeployResourceGroup
    jobs:
      - job: DeployRG
        steps:
          - checkout: self
          - script: echo "Hello world"
