trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: HelloWorldJob
    displayName: 'Run Hello World Script'
    steps:
      - script: echo "Hello World"
        displayName: 'Print Hello World'
